### ISSUE TITLE
How to Setup Authorization on Odoo side?

### ISSUE THREAD

**Issue by itsnot-aduck** [hieuhani/simpos#5]
I see that the app contains Bearer authentication, but maybe native Odoo13 doesn't support this. 

The `simpos_token_authentication` just return the jwt token only, so are there any addons supplyment or code modification here?

Best regard,

**Comment by hieuhani** [comment]
Hi @itsnot-aduck,

It's my issue.

I've added missing file here: https://github.com/hieuhani/simpos/commit/fd16df4cee8512549ffa1537b7085bbc3846a8c3

Thanks,

**Comment by duchm1606** [comment]
> Hi @itsnot-aduck,
> 
> It's my issue.
> 
> I've added missing file here: [fd16df4](https://github.com/hieuhani/simpos/commit/fd16df4cee8512549ffa1537b7085bbc3846a8c3)
> 
> Thanks,

It worked. Btw I want to ask for basic concept of the cors addons, because the http core source has changed since odoo16. Maybe a possible migration to this interesting feature in the future?

**Comment by hieuhani** [comment]
Yes. For sure, I will update this project to the latest Odoo version soon 💪
