### ISSUE TITLE
Email and Password Not Working on Sign-In

### ISSUE THREAD

**Issue by AbelG101** [hieuhani/simpos#7]
Hi Hieu,

I’m having trouble logging in with the default email and password. They don’t seem to be working. Could you please provide guidance on how to access the system?

Thank you!

![image](https://github.com/hieuhani/simpos/assets/104968236/4db39d5f-7429-4a37-97bb-40604f61cb18)

**Comment by AbelG101** [comment]
@hieuhani, I believe the issue is related to CORS, as shown in the screenshot below. I’m experiencing this problem on Firefox, and I’ve also tried it on Microsoft Edge with the same results.

![image](https://github.com/hieuhani/simpos/assets/104968236/5a39d59f-729d-48d7-9899-b297374240cd)

**Comment by hieuhani** [comment]
Hi @AbelG101, the issue is related to my local server, it has been turned off so the 530 error is from Cloudflare proxy. I'm fixing and inform you soon. Sorry

**Comment by hieuhani** [comment]
@AbelG101 The server is up. Please check.
Thank you,

**Comment by helmibe48** [comment]
still cannot to login

**Comment by HassanShanJava** [comment]
@hieuhani I could not login as well.

**Comment by jeffryjdelarosa** [comment]
@hieuhani I cannot logging.
